#!/bin/sh
#copy /usr/bin/bc /usr/bin/bc-backup

cp /usr/bin/bc /usr/bin/bc-backup
mv /usr/local/plan9/bin/bc /usr/bin/bc

cp /bin/ls /bin/ls-backup
mv /usr/local/plan9/bin/ls /bin/ls

cp /bin/mkdir /bin/mkdir-backup
cp /usr/local/plan9/bin/mkdir /bin/mkdir
