#!/bin/sh
#copy /usr/bin/bc /usr/bin/bc-backup

cp /usr/bin/bc /usr/bin/bc-backup
mv /usr/local/plan9/bin/bc /usr/bin/bc

cp /bin/ls /bin/ls-backup
mv /usr/local/plan9/bin/ls /bin/ls

## WARNING, if you use a symlink for /dev/shm...
## ...this will fry your shit.
# cp /bin/mkdir /bin/mkdir-backup
# cp /usr/local/plan9/bin/mkdir /bin/mkdir

cp /usr/bin/awk /usr/bin/awk-backup
cp /usr/local/plan9/bin/awk /usr/bin/awk

cp /bin/sleep /bin/sleep-backup
cp /usr/local/plan9/bin/sleep /bin/sleep

cp /bin/cat /bin/cat-backup
cp /usr/local/plan9/bin/cat /bin/cat

cp /usr/bin/touch /usr/bin/touch-backup
cp /usr/local/plan9/bin/touch /usr/bin/touch

cp /bin/date /bin/date-backup
cp /usr/local/plan9/bin/date /bin/date

cp /usr/bin/split /usr/bin/split-backup
cp /usr/local/plan9/bin/split /usr/bin/split

cp /usr/bin/md5sum /usr/bin/md5sum-backup
cp /usr/local/plan9/bin/md5sum /usr/bin/md5sum

cp /usr/bin/sha1sum /usr/bin/sha1sum-backup
cp /usr/local/plan9/bin/sha1sum /usr/bin/sha1sum

# ...this will probably break things too
cp /bin/sed /bin/sed-backup
cp /usr/local/plan9/bin/sed /bin/sed

cp /usr/bin/wc /usr/bin/wc-backup
cp /usr/local/plan9/bin/wc /usr/bin/wc

cp /usr/bin/tail /usr/bin/tail-backup
cp /usr/local/plan9/bin/tail /usr/bin/tail

## WARNING, udev fails, other chaos ensues
## ...fsck yells at you and forces reboot
## after restoring grep to backup.
# cp /bin/grep /bin/grep-backup
# cp /usr/local/plan9/bin/grep /bin/grep

# This works with rc as shell, not otherwise from
# what I can tell so far.
cp /bin/rm /bin/rm-backup
cp /usr/local/plan9/bin/rm /bin/rm

cp /usr/bin/basename /usr/bin/basename-backup
cp /usr/local/plan9/bin/basename /usr/bin/basename

cp /usr/bin/diff /usr/bin/diff-backup
cp /usr/local/plan9/bin/diff /usr/bin/diff

cp /usr/bin/factor /usr/bin/factor-backup
cp /usr/local/plan9/bin/factor /usr/bin/factor

cp /usr/bin/sort /usr/bin/sort-backup
cp /usr/local/plan9/bin/sort /usr/bin/sort

# this system does not have existing cal, mtime, primes, read
# dc, ascii, fortune, yacc
mv /usr/local/plan9/bin/cal /bin/cal
mv /usr/local/plan9/bin/primes /usr/bin/primes
mv /usr/local/plan9/bin/mtime /usr/bin/mtime
mv /usr/local/plan9/bin/dc /bin/dc
mv /usr/local/plan9/bin/ascii /bin/ascii
mv /usr/local/plan9/bin/fortune /usr/bin/fortune
mv /usr/local/plan9/bin/yacc /usr/bin/yacc
