#!/bin/sh
#copy /usr/bin/bc /usr/bin/bc-backup

cp /usr/bin/bc /usr/bin/bc-backup
mv /usr/local/plan9/bin/bc /usr/bin/bc

cp /bin/ls /bin/ls-backup
mv /usr/local/plan9/bin/ls /bin/ls

## WARNING, if you use a symlink for /dev/shm...
## ...this will fry your shit.
# cp /bin/mkdir /bin/mkdir-backup
# cp /usr/local/plan9/bin/mkdir /bin/mkdir

cp /usr/bin/awk /usr/bin/awk-backup
cp /usr/local/plan9/bin/awk /usr/bin/awk

cp /bin/sleep /bin/sleep-backup
cp /usr/local/plan9/bin/sleep /bin/sleep

cp /bin/cat /bin/cat-backup
cp /usr/local/plan9/bin/cat /bin/cat

cp /usr/bin/touch /usr/bin/touch-backup
cp /usr/local/plan9/bin/touch /usr/bin/touch

cp /bin/date /bin/date-backup
cp /usr/local/plan9/bin/date /bin/date

cp /usr/bin/split /usr/bin/split-backup
cp /usr/local/plan9/bin/split /usr/bin/split

cp /usr/bin/md5sum /usr/bin/md5sum-backup
cp /usr/local/plan9/bin/md5sum /usr/bin/md5sum

cp /usr/bin/sha1sum /usr/bin/sha1sum-backup
cp /usr/local/plan9/bin/sha1sum /usr/bin/sha1sum

# ...this will probably break things too
cp /bin/sed /bin/sed-backup
cp /usr/local/plan9/bin/sed /bin/sed

cp /usr/bin/wc /usr/bin/wc-backup
cp /usr/local/plan9/bin/wc /usr/bin/wc

cp /usr/bin/tail /usr/bin/tail-backup
cp /usr/local/plan9/bin/tail /usr/bin/tail

## WARNING, udev fails, other chaos ensues
## ...fsck yells at you and forces reboot
## after restoring grep to backup.
# cp /bin/grep /bin/grep-backup
# cp /usr/local/plan9/bin/grep /bin/grep

# This works with rc as shell, not otherwise from
# what I can tell so far.
cp /bin/rm /bin/rm-backup
cp /usr/local/plan9/bin/rm /bin/rm

cp /usr/bin/basename /usr/bin/basename-backup
cp /usr/local/plan9/bin/basename /usr/bin/basename

cp /usr/bin/diff /usr/bin/diff-backup
cp /usr/local/plan9/bin/diff /usr/bin/diff

cp /usr/bin/factor /usr/bin/factor-backup
cp /usr/local/plan9/bin/factor /usr/bin/factor

cp /usr/bin/sort /usr/bin/sort-backup
cp /usr/local/plan9/bin/sort /usr/bin/sort

cp /usr/bin/uniq /usr/bin/uniq-backup
cp /usr/local/plan9/bin/uniq /usr/bin/uniq

cp /bin/echo /bin/echo-backup
cp /usr/local/plan9/bin/echo /bin/echo

cp /usr/bin/cmp /usr/bin/cmp-backup
cp /usr/local/plan9/bin/cmp /usr/bin/cmp

cp /usr/bin/sort /usr/bin/sort-backup
cp /usr/local/plan9/bin/sort /usr/bin/sort

cp /usr/bin/seq /usr/bin/seq-backup
cp /usr/local/plan9/bin/seq /usr/bin/seq

cp /usr/bin/strings /usr/bin/strings-backup
cp /usr/local/plan9/bin/strings /usr/bin/strings

cp /usr/bin/tee /usr/bin/tee-backup
cp /usr/local/plan9/bin/tee /usr/bin/tee

cp /usr/bin/troff /usr/bin/troff-backup
cp /usr/local/plan9/bin/troff /usr/bin/troff

cp /usr/bin/join /usr/bin/join-backup
cp /usr/local/plan9/bin/join /usr/bin/join

cp /usr/bin/test /usr/bin/test-backup
cp /usr/local/plan9/bin/test /usr/bin/test

# this system does not have existing cal, mtime, primes, read
# dc, ascii, fortune, yacc, look, cleanname(duh), read, pbd
# ed, hoc, sam, listen1, unicode, ssam, getflags, 

mv /usr/local/plan9/bin/cal /bin/cal
mv /usr/local/plan9/bin/primes /usr/bin/primes
mv /usr/local/plan9/bin/mtime /usr/bin/mtime
mv /usr/local/plan9/bin/dc /bin/dc
mv /usr/local/plan9/bin/ascii /bin/ascii
mv /usr/local/plan9/bin/fortune /usr/bin/fortune
mv /usr/local/plan9/bin/yacc /usr/bin/yacc
mv /usr/local/plan9/bin/look /usr/bin/look
mv /usr/local/plan9/bin/cleanname /usr/bin/cleanname
mv /usr/local/plan9/bin/read /usr/bin/read
mv /usr/local/plan9/bin/pbd /usr/bin/pbd
mv /usr/local/plan9/bin/ed /usr/bin/ed
mv /usr/local/plan9/bin/hoc /usr/bin/hoc
mv /usr/local/plan9/bin/sam /usr/bin/sam
mv /usr/local/plan9/bin/listen1 /usr/bin/listen1
mv /usr/local/plan9/bin/unicode /usr/bin/unicode
mv /usr/local/plan9/bin/ssam /usr/bin/ssam
mv /usr/local/plan9/bin/getflags /usr/bin/getflags
